import type {
  Agent,
  AuditLog,
  Memory,
  Permission,
  Project,
  Task,
} from "@weios/shared-types";

const createdAt = "2026-06-30T00:00:00.000Z";

export const seedTasks: Task[] = [
  {
    id: "task_weios_bootstrap",
    title: "Initialize WeiOS monorepo",
    description: "Create shared types, API skeleton, docs, and client shells.",
    projectId: "project_weios",
    priority: "critical",
    status: "doing",
    source: "planning-doc",
    owner: "Wei",
    createdBy: "user",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "task_planfit_builder_api",
    title: "Confirm Builder API timeline",
    description: "Validate whether the Builder API has a July delivery risk.",
    projectId: "project_planfit",
    priority: "high",
    status: "todo",
    source: "planning-doc-example",
    owner: "Wei",
    createdBy: "ai",
    createdAt,
    updatedAt: createdAt,
  },
];

export const seedMemories: Memory[] = [
  {
    id: "memory_weios_principle",
    type: "long_term",
    title: "WeiOS core principle",
    content:
      "Not people around tools, but all tools, data, and AI around the person.",
    source: "planning-doc",
    projectId: "project_weios",
    tags: ["principle", "identity", "context"],
    confidence: 0.98,
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "memory_mvp_focus",
    type: "decision",
    title: "MVP focuses on Project Hub, Memory Engine, and AI Summary",
    content:
      "The first phase should not integrate WeChat, DingTalk, trading, or production deployment automation.",
    source: "planning-doc",
    projectId: "project_weios",
    tags: ["mvp", "decision", "scope"],
    confidence: 0.97,
    createdAt,
    updatedAt: createdAt,
  },
];

export const seedProjects: Project[] = [
  {
    id: "project_weios",
    name: "WeiOS / KnowMe v2.0",
    description:
      "Personal AI operating system for memory, projects, AI workflows, and permission-first automation.",
    status: "active",
    priority: 1,
    goals: ["Project Hub", "Memory Engine", "AI Summary", "Security Center"],
    currentState: "Monorepo bootstrap in progress.",
    nextActions: seedTasks.filter((task) => task.projectId === "project_weios"),
    risks: [
      {
        id: "risk_scope_creep",
        title: "MVP scope creep",
        description:
          "Integrating chat apps and finance automation too early would delay the core brain.",
        severity: "high",
        status: "monitoring",
        owner: "Wei",
        createdAt,
      },
    ],
    documents: [
      {
        id: "doc_planning_v01",
        title: "WeiOS planning document v0.1",
        pathOrUrl:
          "/Users/shangwei/Downloads/WeiOS_Personal_AI_Operating_System_规划文档_v0.1.docx",
        kind: "doc",
      },
    ],
    relatedMemories: seedMemories.filter(
      (memory) => memory.projectId === "project_weios",
    ),
    relatedPeople: [],
    repositories: [],
    updatedAt: createdAt,
  },
  {
    id: "project_planfit",
    name: "Planfit Australia Real Estate Platform",
    description:
      "Real estate platform workstream with Builder API and launch timeline risks.",
    status: "active",
    priority: 2,
    goals: ["Clarify Builder API delivery", "Track launch blockers"],
    currentState: "Needs structured project memory and risk tracking.",
    nextActions: seedTasks.filter(
      (task) => task.projectId === "project_planfit",
    ),
    risks: [
      {
        id: "risk_builder_api_delay",
        title: "Builder API delivery may slip",
        description:
          "Planning example indicates a possible delay to late July.",
        severity: "high",
        status: "open",
        owner: "Wei",
        createdAt,
      },
    ],
    documents: [],
    relatedMemories: [],
    relatedPeople: [
      {
        id: "person_chris",
        name: "Chris",
        relationship: "Planfit collaborator",
        notes: "Mentioned in the planning example as tied to Builder API risk.",
      },
    ],
    repositories: [],
    updatedAt: createdAt,
  },
  {
    id: "project_itms",
    name: "iTMS",
    description: "Existing project to bring under WeiOS project memory.",
    status: "active",
    priority: 3,
    goals: ["Centralize status", "Track risks", "Preserve decisions"],
    currentState: "Awaiting initial import.",
    nextActions: [],
    risks: [],
    documents: [],
    relatedMemories: [],
    relatedPeople: [],
    repositories: [],
    updatedAt: createdAt,
  },
  {
    id: "project_flutter_finance",
    name: "Flutter Finance",
    description: "Personal finance management app and finance assistant path.",
    status: "active",
    priority: 4,
    goals: ["Asset overview", "Risk reminders", "Decision records"],
    currentState: "Finance automation must remain analysis-only for MVP.",
    nextActions: [],
    risks: [],
    documents: [],
    relatedMemories: [],
    relatedPeople: [],
    repositories: [],
    updatedAt: createdAt,
  },
  {
    id: "project_ai_video",
    name: "AI Video",
    description: "AI video project pool entry.",
    status: "idea",
    priority: 5,
    goals: ["Capture context", "Track next experiments"],
    currentState: "In future project pool.",
    nextActions: [],
    risks: [],
    documents: [],
    relatedMemories: [],
    relatedPeople: [],
    repositories: [],
    updatedAt: createdAt,
  },
  {
    id: "project_ielts",
    name: "IELTS Learning",
    description: "Learning project for English study planning and progress.",
    status: "active",
    priority: 6,
    goals: ["Track study plan", "Capture learning memory"],
    currentState: "Awaiting initial import.",
    nextActions: [],
    risks: [],
    documents: [],
    relatedMemories: [],
    relatedPeople: [],
    repositories: [],
    updatedAt: createdAt,
  },
  {
    id: "project_investment",
    name: "Investment Management",
    description: "Investment context, decisions, risk notes, and cash planning.",
    status: "active",
    priority: 7,
    goals: ["Decision records", "Risk reminders", "Cash-flow planning"],
    currentState: "AI may analyze but must not trade or move money.",
    nextActions: [],
    risks: [],
    documents: [],
    relatedMemories: [],
    relatedPeople: [],
    repositories: [],
    updatedAt: createdAt,
  },
];

export const seedAgents: Agent[] = [
  {
    id: "agent_planner",
    name: "Planner",
    role: "planner",
    provider: "openai",
    model: "gpt-5",
    permissions: ["project.read", "memory.read", "task.write"],
    enabled: true,
  },
  {
    id: "agent_architect",
    name: "Architect",
    role: "architect",
    provider: "anthropic",
    model: "claude",
    permissions: ["project.read", "memory.read"],
    enabled: true,
  },
  {
    id: "agent_coder",
    name: "Coder",
    role: "coder",
    provider: "local",
    model: "codex",
    permissions: ["project.read", "memory.read", "task.write"],
    enabled: true,
  },
];

export const seedPermissions: Permission[] = [
  {
    id: "permission_project_read",
    scope: "project.read",
    riskLevel: "green",
    description: "Read project state and project documents in approved paths.",
    requiresApproval: false,
    enabled: true,
  },
  {
    id: "permission_memory_write",
    scope: "memory.write",
    riskLevel: "yellow",
    description: "Persist durable memory items.",
    requiresApproval: true,
    enabled: true,
  },
  {
    id: "permission_external_write",
    scope: "external.write",
    riskLevel: "red",
    description: "Send outbound messages or write to external systems.",
    requiresApproval: true,
    enabled: false,
  },
  {
    id: "permission_finance_trade",
    scope: "finance.trade",
    riskLevel: "red",
    description: "Trade assets or move money.",
    requiresApproval: true,
    enabled: false,
  },
];

export const seedAuditLogs: AuditLog[] = [
  {
    id: "audit_bootstrap",
    actor: "system",
    action: "Initialize WeiOS skeleton",
    target: "local workspace",
    riskLevel: "green",
    status: "executed",
    result: "Created monorepo, shared types, docs, and service skeleton.",
    timestamp: createdAt,
  },
];
